[package]
name = "vrungel"
version = "0.1.0"
authors = ["b7w@isudo.ru <b7w@isudo.ru>"]

[dependencies]
docopt = "1"
serde = "1.0"
serde_derive = "1.0"
subprocess = "0.1.15"
actix-web = "0.7"
log = "0.4"
simple_logger = "1.0"
